# Generated by Django 4.2.4 on 2023-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='third_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='1', max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
    ]
